before_script:
  - mkdir -p ~/yocto-webkit
  - cd ~/yocto-webkit
  - ulimit -n 4096
  - repo init -u https://gitlab.com/saavedra.pablo/meta-perf-browser.git -m $MANIFEST -b nightly
  - repo sync --force-sync
  - pushd sources/meta-webkit
  - git remote remove tmp || true
  - git remote add tmp $CI_REPOSITORY_URL
  - git fetch tmp
  - git checkout $CI_COMMIT_SHA
  - popd
  - source setup-environment $SOURCE
  - rm -rf tmp

warrior-wandboard-mesa-weston-wpe-2.20:
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: wandboard-mesa-wpe-2.20 wandboard-mesa browsers default mesa-wpe-2_20 --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

warrior-wandboard-mesa-weston-wpe-2.22:
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: wandboard-mesa-wpe-2.22 wandboard-mesa browsers default mesa-wpe-2_22 --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

warrior-wandboard-mesa-weston-wpe-2.24:
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: wandboard-mesa-wpe-2.24 wandboard-mesa browsers default mesa-wpe-2_24 --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

warrior-wandboard-mesa-weston-wpe-trunk:
  allow_failure: true
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: wandboard-mesa-wpe-trunk wandboard-mesa browsers default mesa-wpe-trunk --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

warrior-wandboard-mesa-weston-wpe-qt:
  allow_failure: true
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: wandboard-mesa-wpe-qt wandboard-mesa browsers default mesa-wpe-qt --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

warrior-rpi3-userland-wpe-2.22:
  tags:
    - meta-webkit
  variables:
    MANIFEST: manifest-warrior.xml
    # setup-environment targetname machine distro bblayers presets --update-config
    SOURCE: rpi3-userland-wpe-2.22 raspberrypi3-userland browsers default userland-wpe-2_22 --update-config
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp
